name: Automated Tests
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: greetings
        run: date
      - name: checkout main
        uses: actions/checkout@v3
      - name: nodejs dependencies
        run: npm ci
      - name: automated tests
        run: npm test
