name: Automated Tests
on: [ workflow_dispatch, push ]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: greetings
        run: date
      - name: checkout sample nodejs React project
        uses: actions/checkout@v3
      - name: ensure nodejs dependencies are installed
        run: npm ci
      - name: run automated tests
        run: npm test
      - name: goodbye
        run: date
