name: Automated Tests
on: [ workflow_dispatch, push ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: greetings
        run: date
      - name: past history
        run: fc -l
      - name: pwd
        run: pwd
      - name: ls
        run: ls -alF
      - name: nodejs install
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: checkout sample nodejs React project
        uses: actions/checkout@v3
      - name: ensure nodejs dependencies are installed
        run: npm ci
      - name: run automated tests
        run: npm test
      - name: goodbye
        run: date
